#!/bin/bash
echo "Husky pre-commit has triggered"

# Check for changes in specific file types in the frontend directory
CHANGES=$(git diff --cached --name-only | grep '^doca_fe/.*\.\(js\|jsx\|ts\|tsx\|css\|json\|md\)$')

if [ -z "$CHANGES" ]; then
  echo "✅ No changes in the frontend directory. Skipping Prettier"
  exit 0
fi

# Navigate to the frontend directory
cd doca_fe

# Check for missing dependencies
echo "🔍 Checking dependencies..."
npm run check-dependencies
if [ $? -ne 0 ]; then
  echo "❌ Missing dependencies in the frontend. Please run 'npm install' in the frontend directory and try again."
  exit 1
fi

# Run Prettier and other pre-commit tasks
echo "🔧 Running Prettier and pre-commit tasks..."
npm run pre-commit